[project]
name = "curamente"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-extensions>=4.1",
    "djangorestframework>=3.16.0",
    "httpie>=3.2.4",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-django>=4.11.1",
    "pytest-mock>=3.14.1",
    "pytest-subtests>=0.14.2",
    "pytest-xdist[psutil]>=3.8.0",
    "ruff>=0.12.7",
]
