# Generated by Django 5.0.6 on 2024-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pacientes",
            field=models.ManyToManyField(blank=True, null=True, to="core.profile"),
        ),
    ]
